### ISSUE TITLE
Can't build with the redistHelper

### ISSUE THREAD

**Issue by bigasdev** [deepnight/minisiteBase#1]
Trying to build an app using the command `haxelib run redistHelper js.hxml -o redist docs/css docs/js docs/index.html -ignore style.css,*.scss,*.map` and getting the following issue:

`C:\HaxeToolkit\haxe\lib\heaps/1,9,1/hxd/Res.hx:4: characters 1-8 : Warning : Resource directory not found in classpath 'res' (use -D resourcesPath=DIR)
C:\HaxeToolkit\haxe\lib\heaps/1,9,1/hxd/Res.hx:4: characters 1-8 : Uncaught exception __invalid: No such file or directory
C:\HaxeToolkit\haxe\lib\heaps/1,9,1/hxd/res/FileTree.hx:96: characters 13-46 : Called from here
C:\HaxeToolkit\haxe\lib\heaps/1,9,1/hxd/res/FileTree.hx:64: characters 4-20 : Called from here
C:\HaxeToolkit\haxe\lib\heaps/1,9,1/hxd/res/FileTree.hx:264: characters 18-24 : Called from here
C:\HaxeToolkit\haxe\lib\heaps/1,9,1/hxd/res/FileTree.hx:375: characters 10-41 : Called from here
C:\HaxeToolkit\haxe\lib\heaps/1,9,1/hxd/Res.hx:4: characters 1-8 : Called from here
src/Boot.hx:1: lines 1-15 : ... Defined in this class`

**Comment by deepnight** [comment]
Sorry, this should be fixed now!
